version: '3'

services:
  mongo-bot:
    image: mongo:8.0.5
    container_name: mongo-bot
    env_file:
      - mongo.env
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-bot:
    image: redis:latest
    container_name: redis-bot
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    depends_on:
      mongo-bot:
        condition: service_healthy
      redis-bot:
        condition: service_healthy
      


